[build]
  command = "rm -rf node_modules package-lock.json .next && npm install && npx prisma generate && next build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  directory = ".netlify/functions-internal"

[build.environment]
  NODE_VERSION = "22"
  NEXT_RUNTIME = "nodejs"
  DATABASE_URL = "postgresql://postgres.fuqckantlgtrxywahdxx:6rDz%25%2By6%2CR8DgAm@aws-1-ap-southeast-1.pooler.supabase.com:6543/postgres"
